### PR TITLE
feat: cicle-ci

### PR DESCRIPTION
**Pull request by agustinhoo**

### CODE REVIEW

**Comment by agustinhoo** [comment]
Adds circle-ci

**Comment by ozbillwang** [comment]
obviously it would be that simple. closed

**Comment by ozbillwang** [comment]
thanks to recommand this image "https://hub.docker.com/r/cimg/deploy" to run the docker build in CircleCI. 

I am going to switch Circle CI with multi-arch builds, if i can't make it work quickly, will accept your way first.

**Comment by ozbillwang** [comment]
Close, since I have done the multi-arch image build in CircleCI

**Pull request closed without merging**
