### PR TITLE
fix typo in README

### PR DESCRIPTION
**Pull request by bclermont**

### CODE REVIEW

**Comment by bclermont** [comment]
also 3.2.0 and 2.6.6 are out

**Comment by ozbillwang** [comment]
Regarding v3.2.0, it was released less than 10 hours, the daily job should be fine to pick it up soon in next bbuild.

Since your change has been merged just now, it triggers the build, so this version was published already.

**Comment by ozbillwang** [comment]
For version 2.6.6, it was missed.  Now I can't list its version with below command any more. 
```
repo="helm/helm"
curl -sL https://api.github.com/repos/${repo}/tags |jq -r ".[].name"|sort -Vr
```

**Comment by ozbillwang** [comment]
by the way, I went through the official site, I don't see the version of v2.6.6

I can only see the tag of v2.6.0, v2.6.1 and v2.6.2

https://github.com/helm/helm/tags?after=v2.7.0-rc1

**Pull request merged**
